/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as ApiLiveTokenRouteImport } from './routes/api/live-token'
import { Route as ApiIngestTextRouteImport } from './routes/api/ingest-text'
import { Route as ApiIngestRouteImport } from './routes/api/ingest'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as SlugChatRouteImport } from './routes/$slug.chat'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveTokenRoute = ApiLiveTokenRouteImport.update({
  id: '/api/live-token',
  path: '/api/live-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestTextRoute = ApiIngestTextRouteImport.update({
  id: '/api/ingest-text',
  path: '/api/ingest-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugChatRoute = SlugChatRouteImport.update({
  id: '/$slug/chat',
  path: '/$slug/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/$slug/chat': typeof SlugChatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/ingest-text': typeof ApiIngestTextRoute
  '/api/live-token': typeof ApiLiveTokenRoute
  '/$slug/': typeof SlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/$slug/chat': typeof SlugChatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/ingest-text': typeof ApiIngestTextRoute
  '/api/live-token': typeof ApiLiveTokenRoute
  '/$slug': typeof SlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/$slug/chat': typeof SlugChatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/ingest-text': typeof ApiIngestTextRoute
  '/api/live-token': typeof ApiLiveTokenRoute
  '/$slug/': typeof SlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/$slug/chat'
    | '/api/chat'
    | '/api/ingest'
    | '/api/ingest-text'
    | '/api/live-token'
    | '/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/$slug/chat'
    | '/api/chat'
    | '/api/ingest'
    | '/api/ingest-text'
    | '/api/live-token'
    | '/$slug'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/$slug/chat'
    | '/api/chat'
    | '/api/ingest'
    | '/api/ingest-text'
    | '/api/live-token'
    | '/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SlugChatRoute: typeof SlugChatRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiIngestRoute: typeof ApiIngestRoute
  ApiIngestTextRoute: typeof ApiIngestTextRoute
  ApiLiveTokenRoute: typeof ApiLiveTokenRoute
  SlugIndexRoute: typeof SlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/$slug'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-token': {
      id: '/api/live-token'
      path: '/api/live-token'
      fullPath: '/api/live-token'
      preLoaderRoute: typeof ApiLiveTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest-text': {
      id: '/api/ingest-text'
      path: '/api/ingest-text'
      fullPath: '/api/ingest-text'
      preLoaderRoute: typeof ApiIngestTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/chat': {
      id: '/$slug/chat'
      path: '/$slug/chat'
      fullPath: '/$slug/chat'
      preLoaderRoute: typeof SlugChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SlugChatRoute: SlugChatRoute,
  ApiChatRoute: ApiChatRoute,
  ApiIngestRoute: ApiIngestRoute,
  ApiIngestTextRoute: ApiIngestTextRoute,
  ApiLiveTokenRoute: ApiLiveTokenRoute,
  SlugIndexRoute: SlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
